// <auto-generated />
using System;
using KOP.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace KOP.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KOPDbContext))]
    [Migration("20260807085027_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KOP.Domain.Entities.AccessGrant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GranteeOrgUnitId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("GRANTEE_ORG_UNIT_ID");

                    b.Property<int?>("GranteeUserId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("GRANTEE_USER_ID");

                    b.Property<DateTime>("InsertedAt")
                        .HasPrecision(3)
                        .HasColumnType("TIMESTAMP(3)")
                        .HasColumnName("INSERTED_AT");

                    b.Property<int>("InsertedByUserId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("INSERTED_BY_USER_ID");

                    b.Property<int>("Permissions")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PERMISSIONS");

                    b.Property<int>("ResponsibleOrgUnitId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RESPONSIBLE_ORG_UNIT_ID");

                    b.Property<int>("YpodeigmaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("YPODEIGMA_ID");

                    b.HasKey("Id");

                    b.HasIndex("GranteeOrgUnitId");

                    b.HasIndex("GranteeUserId");

                    b.HasIndex("InsertedByUserId");

                    b.HasIndex("ResponsibleOrgUnitId");

                    b.HasIndex("YpodeigmaId", "ResponsibleOrgUnitId");

                    b.ToTable("SEC_ACCESS_GRANTS", null, t =>
                        {
                            t.HasCheckConstraint("CK_ACCESS_GRANTS_EXACTLY_ONE_GRANTEE", "(\r\n    (\"GRANTEE_USER_ID\" IS NOT NULL AND \"GRANTEE_ORG_UNIT_ID\" IS NULL)\r\n    OR\r\n    (\"GRANTEE_USER_ID\" IS NULL AND \"GRANTEE_ORG_UNIT_ID\" IS NOT NULL)\r\n)");
                        });
                });

            modelBuilder.Entity("KOP.Domain.Entities.Ale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Katigoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("KATIGORIA");

                    b.Property<string>("Kodikos")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("KODIKOS");

                    b.Property<string>("Perigrafi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("PERIGRAFI");

                    b.HasKey("Id");

                    b.HasIndex("Kodikos")
                        .IsUnique();

                    b.ToTable("REF_ALE", (string)null);
                });

            modelBuilder.Entity("KOP.Domain.Entities.KatigoriaPtitikouMesou", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Onomasia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("ONOMASIA");

                    b.HasKey("Id");

                    b.ToTable("REF_KATIGORIES_PTITIKON_MESON", (string)null);
                });

            modelBuilder.Entity("KOP.Domain.Entities.KyrioStoixeio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Onomasia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("ONOMASIA");

                    b.Property<string>("Perigrafi")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("PERIGRAFI");

                    b.HasKey("Id");

                    b.ToTable("REF_KYRIA_STOIXEIA", (string)null);
                });

            modelBuilder.Entity("KOP.Domain.Entities.MiktesApodoxesAnaEtosOrgUnitStoixeioKostous", b =>
                {
                    b.Property<int>("EtosAnaforas")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ETOS_ANAFORAS");

                    b.Property<int>("OrgUnitId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ORG_UNIT_ID");

                    b.Property<int>("StoixeioKostousId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STOIXEIO_KOSTOUS_ID");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("VALUE");

                    b.HasKey("EtosAnaforas", "OrgUnitId", "StoixeioKostousId");

                    b.HasIndex("OrgUnitId");

                    b.HasIndex("StoixeioKostousId");

                    b.ToTable("CALC_ST1_MIKTES_APODOXES_ANA_ETOS_ORG_UNIT_STOIXEIO_KOSTOUS", (string)null);
                });

            modelBuilder.Entity("KOP.Domain.Entities.OrganizationalUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HstrId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("HSTR_ID");

                    b.Property<string>("Onomasia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("ONOMASIA");

                    b.Property<int?>("ParentId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PARENT_ID");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("UNIT_TYPE");

                    b.HasKey("Id");

                    b.HasIndex("HstrId")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("REF_ORGANIZATIONAL_UNITS", (string)null);
                });

            modelBuilder.Entity("KOP.Domain.Entities.StoixeioKostous", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EinaiXamiloteroEpipedo")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("EINAI_XAMILOTERO_EPIPEDO");

                    b.Property<int>("EpipedoAnalysis")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EPIPEDO_ANALYSIS");

                    b.Property<string>("Kodikos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("KODIKOS");

                    b.Property<int>("KyrioStoixeioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("KYRIO_STOIXEIO_ID");

                    b.Property<string>("Onomasia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("ONOMASIA");

                    b.HasKey("Id");

                    b.HasIndex("KyrioStoixeioId");

                    b.ToTable("REF_STOIXEIA_KOSTOUS", (string)null);
                });

            modelBuilder.Entity("KOP.Domain.Entities.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("COMMENT");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("TIMESTAMP(3)")
                        .HasColumnName("CREATED_AT");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CREATED_BY_USER_ID");

                    b.Property<int>("CurrentRevisionNo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CURRENT_REVISION_NO");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CURRENT_STATUS");

                    b.Property<int>("EtosAnaforas")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ETOS_ANAFORAS");

                    b.Property<int>("ResponsibleOrgUnitId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RESPONSIBLE_ORG_UNIT_ID");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("TIMESTAMP(3)")
                        .HasColumnName("UPDATED_AT");

                    b.Property<int>("UpdatedByUserId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("UPDATED_BY_USER_ID");

                    b.Property<int>("YpodeigmaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("YPODEIGMA_ID");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ResponsibleOrgUnitId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("YpodeigmaId", "EtosAnaforas", "ResponsibleOrgUnitId")
                        .IsUnique();

                    b.ToTable("WF_SUBMISSIONS", (string)null);
                });

            modelBuilder.Entity("KOP.Domain.Entities.SubmissionEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("COMMENT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("STATUS");

                    b.Property<DateTime>("StatusChangedAt")
                        .HasPrecision(3)
                        .HasColumnType("TIMESTAMP(3)")
                        .HasColumnName("STATUS_CHANGED_AT");

                    b.Property<int>("StatusChangedByUserId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS_CHANGED_BY_USER_ID");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SUBMISSION_ID");

                    b.Property<int>("SubmissionRevisionNo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SUBMISSION_REVISION_NO");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("StatusChangedByUserId");

                    b.HasIndex("SubmissionId", "SubmissionRevisionNo");

                    b.ToTable("WF_SUBMISSION_EVENTS", (string)null);
                });

            modelBuilder.Entity("KOP.Domain.Entities.SubmissionSubjectOrgUnit", b =>
                {
                    b.Property<int>("SubmissionId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SUBMISSION_ID");

                    b.Property<int>("SubjectOrgUnitId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SUBJECT_ORG_UNIT_ID");

                    b.HasKey("SubmissionId", "SubjectOrgUnitId");

                    b.HasIndex("SubjectOrgUnitId")
                        .HasDatabaseName("IX_SubmissionSubjectOrgUnits_SUBJECT_ORG_UNIT_ID");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("IX_SubmissionSubjectOrgUnits_SUBMISSION_ID");

                    b.ToTable("WF_SUBMISSIONS_SUBJECTS_ORG_UNITS", (string)null);
                });

            modelBuilder.Entity("KOP.Domain.Entities.TopothetisiStelexous", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ama")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("AMA");

                    b.Property<int?>("ApospasiSe")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("APOSPASI_SE_HSTR_ID");

                    b.Property<string>("ApospasiSeTitle")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("APOSPASI_SE_HSTR_TITLE");

                    b.Property<DateTime>("DateDiagrafisEtous")
                        .HasColumnType("DATE")
                        .HasColumnName("DATE_DIAGRAFIS_ETOUS");

                    b.Property<DateTime>("DateParousiasisEtous")
                        .HasColumnType("DATE")
                        .HasColumnName("DATE_PAROUSIASIS_ETOUS");

                    b.Property<string>("Eidik")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("EIDIK");

                    b.Property<bool>("EinaiApospasi")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("EINAI_APOSPASI");

                    b.Property<string>("Eponymo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EPONYMO");

                    b.Property<int>("EtosAnaforas")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ETOS_ANAFORAS");

                    b.Property<bool>("ExeiApospaseisStoDiastimaTopothetisis")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("EXEI_APOSPASEIS_STO_DIASTIMA_TOPOTHETISIS");

                    b.Property<int>("HstrId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("HSTR_ID");

                    b.Property<int>("HstrIdMonadas")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("HSTR_ID_MONADAS");

                    b.Property<string>("HstrTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("HSTR_TITLE");

                    b.Property<string>("HstrTitleMonadas")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("HSTR_TITLE_MONADAS");

                    b.Property<int>("Imeres")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IMERES");

                    b.Property<string>("Onoma")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("ONOMA");

                    b.Property<int>("OrgUnitId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ORG_UNIT_ID");

                    b.Property<int>("PebadaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PEBADA_ID");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("RANK");

                    b.Property<int>("StoixeioKostousId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STOIXEIO_KOSTOUS_ID");

                    b.Property<decimal>("SynoloMiktonApodoxonStelexousStisImeres")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("SYNOLO_MIKTON_APODOXON_STELEXOUS_STIS_IMERES");

                    b.HasKey("Id");

                    b.HasIndex("HstrIdMonadas");

                    b.HasIndex("OrgUnitId");

                    b.HasIndex("PebadaId");

                    b.HasIndex("StoixeioKostousId");

                    b.HasIndex("EtosAnaforas", "OrgUnitId");

                    b.HasIndex("EtosAnaforas", "PebadaId");

                    b.ToTable("INP_ST1_TOPOTHETISEIS_PROSOPIKOU", (string)null);
                });

            modelBuilder.Entity("KOP.Domain.Entities.TyposPtitikouMesou", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KatigoriaPtitikouMesouId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("KATIGORIA_PTITIKOU_MESOU_ID");

                    b.Property<string>("Onomasia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("ONOMASIA");

                    b.HasKey("Id");

                    b.HasIndex("KatigoriaPtitikouMesouId");

                    b.ToTable("REF_TYPOI_PTITIKON_MESON", (string)null);
                });

            modelBuilder.Entity("KOP.Domain.Entities.TyposPtitikouMesouOrgUnit", b =>
                {
                    b.Property<int>("TyposPtitikouMesouId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TYPOS_PTITIKOU_MESOU_ID");

                    b.Property<int>("OrgUnitId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ORG_UNIT_ID");

                    b.HasKey("TyposPtitikouMesouId", "OrgUnitId");

                    b.HasIndex("OrgUnitId");

                    b.ToTable("REF_TYPOI_PTITIKON_MESON_ORG_UNITS", (string)null);
                });

            modelBuilder.Entity("KOP.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AMA")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("AMA");

                    b.Property<string>("Eidikotita")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("EIDIKOTITA");

                    b.Property<string>("Epistasia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EPISTASIA");

                    b.Property<string>("Eponymo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EPONYMO");

                    b.Property<int>("ExternalId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EXTERNAL_ID");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Onoma")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("ONOMA");

                    b.Property<int>("OrgUnitId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ORG_UNIT_ID");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("PHONE_NUMBER");

                    b.Property<string>("Vathmos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("VATHMOS");

                    b.HasKey("Id");

                    b.HasIndex("AMA");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("OrgUnitId");

                    b.ToTable("SEC_USERS", (string)null);
                });

            modelBuilder.Entity("KOP.Domain.Entities.ValueForAleOdoiporikon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AleId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ALE_ID");

                    b.Property<int>("EntryId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ENTRY_ID");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("VALUE");

                    b.HasKey("Id");

                    b.HasIndex("AleId");

                    b.HasIndex("EntryId", "AleId")
                        .IsUnique();

                    b.ToTable("INP_VALUES_FOR_ALE_ODOIPORIKON", (string)null);
                });

            modelBuilder.Entity("KOP.Domain.Entities.Ypodeigma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<int>("KyrioStoixeioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("KYRIO_STOIXEIO_ID");

                    b.Property<string>("Perigrafi")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("PERIGRAFI");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("TITLE");

                    b.Property<string>("YpodeigmaType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("YPODEIGMA_TYPE");

                    b.HasKey("Id");

                    b.HasIndex("KyrioStoixeioId");

                    b.ToTable("REF_YPODEIGMATA", (string)null);
                });

            modelBuilder.Entity("KOP.Domain.Entities.YpodeigmaEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("COMMENT");

                    b.Property<int?>("MoiraOrgUnitId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MOIRA_ORG_UNIT_ID");

                    b.Property<int>("MonadaOrgUnitId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MONADA_ORG_UNIT_ID");

                    b.Property<int>("StoixeioKostousId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STOIXEIO_KOSTOUS_ID");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SUBMISSION_ID");

                    b.Property<int>("SubmissionRevisionNo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SUBMISSION_REVISION_NO");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("VALUE");

                    b.HasKey("Id");

                    b.HasIndex("MoiraOrgUnitId");

                    b.HasIndex("MonadaOrgUnitId");

                    b.HasIndex("StoixeioKostousId");

                    b.HasIndex("SubmissionId", "SubmissionRevisionNo");

                    b.ToTable("INP_YPODEIGMATA_ENTRIES", (string)null);
                });

            modelBuilder.Entity("KOP.Domain.Entities.YpodeigmaSubmissionScope", b =>
                {
                    b.Property<int>("YpodeigmaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("YPODEIGMA_ID");

                    b.Property<int>("ResponsibleOrgUnitId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RESPONSIBLE_ORG_UNIT_ID");

                    b.Property<int>("SubjectOrgUnitId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SUBJECT_ORG_UNIT_ID");

                    b.HasKey("YpodeigmaId", "ResponsibleOrgUnitId", "SubjectOrgUnitId");

                    b.HasIndex("ResponsibleOrgUnitId")
                        .HasDatabaseName("IX_YpodeigmaSubmissionScopes_RESPONSIBLE_ORG_UNIT_ID");

                    b.HasIndex("SubjectOrgUnitId")
                        .HasDatabaseName("IX_YpodeigmaSubmissionScopes_SUBJECT_ORG_UNIT_ID");

                    b.HasIndex("YpodeigmaId")
                        .HasDatabaseName("IX_YpodeigmaSubmissionScopes_YPODEIGMA_ID");

                    b.HasIndex("YpodeigmaId", "ResponsibleOrgUnitId")
                        .HasDatabaseName("IX_YpodeigmaSubmissionScopes_YPODEIGMA_ID_RESPONSIBLE_ORG_UNIT_ID");

                    b.ToTable("REF_YPODEIGMA_SUBMISSION_SCOPES", (string)null);
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USER_ID");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ROLE");

                    b.Property<DateTime>("InsertedAt")
                        .HasPrecision(3)
                        .HasColumnType("TIMESTAMP(3)")
                        .HasColumnName("INSERTED_AT");

                    b.Property<int>("InsertedByUserId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("INSERTED_BY_USER_ID");

                    b.HasKey("UserId", "Role");

                    b.HasIndex("InsertedByUserId");

                    b.ToTable("SEC_USERS_ROLES", (string)null);
                });

            modelBuilder.Entity("KOP.Domain.Entities.AccessGrant", b =>
                {
                    b.HasOne("KOP.Domain.Entities.OrganizationalUnit", "GranteeOrgUnit")
                        .WithMany()
                        .HasForeignKey("GranteeOrgUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KOP.Domain.Entities.User", "GranteeUser")
                        .WithMany("ReceivedAccessGrants")
                        .HasForeignKey("GranteeUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KOP.Domain.Entities.User", "InsertedByUser")
                        .WithMany("InsertedAccessGrants")
                        .HasForeignKey("InsertedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KOP.Domain.Entities.OrganizationalUnit", "ResponsibleOrgUnit")
                        .WithMany()
                        .HasForeignKey("ResponsibleOrgUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KOP.Domain.Entities.Ypodeigma", "Ypodeigma")
                        .WithMany()
                        .HasForeignKey("YpodeigmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GranteeOrgUnit");

                    b.Navigation("GranteeUser");

                    b.Navigation("InsertedByUser");

                    b.Navigation("ResponsibleOrgUnit");

                    b.Navigation("Ypodeigma");
                });

            modelBuilder.Entity("KOP.Domain.Entities.MiktesApodoxesAnaEtosOrgUnitStoixeioKostous", b =>
                {
                    b.HasOne("KOP.Domain.Entities.OrganizationalUnit", "OrgUnit")
                        .WithMany("MiktesApodoxesAnaEtosOrgUnitStoixeioKostous")
                        .HasForeignKey("OrgUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KOP.Domain.Entities.StoixeioKostous", "StoixeioKostous")
                        .WithMany("MiktesApodoxesAnaEtosOrgUnitStoixeioKostous")
                        .HasForeignKey("StoixeioKostousId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrgUnit");

                    b.Navigation("StoixeioKostous");
                });

            modelBuilder.Entity("KOP.Domain.Entities.OrganizationalUnit", b =>
                {
                    b.HasOne("KOP.Domain.Entities.OrganizationalUnit", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("KOP.Domain.Entities.StoixeioKostous", b =>
                {
                    b.HasOne("KOP.Domain.Entities.KyrioStoixeio", "KyrioStoixeio")
                        .WithMany("StoixeiaKostous")
                        .HasForeignKey("KyrioStoixeioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KyrioStoixeio");
                });

            modelBuilder.Entity("KOP.Domain.Entities.Submission", b =>
                {
                    b.HasOne("KOP.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedSubmissions")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KOP.Domain.Entities.OrganizationalUnit", "ResponsibleOrgUnit")
                        .WithMany("Submissions")
                        .HasForeignKey("ResponsibleOrgUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KOP.Domain.Entities.User", "UpdatedByUser")
                        .WithMany("UpdatedSubmissions")
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KOP.Domain.Entities.Ypodeigma", "Ypodeigma")
                        .WithMany("Submissions")
                        .HasForeignKey("YpodeigmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("ResponsibleOrgUnit");

                    b.Navigation("UpdatedByUser");

                    b.Navigation("Ypodeigma");
                });

            modelBuilder.Entity("KOP.Domain.Entities.SubmissionEvent", b =>
                {
                    b.HasOne("KOP.Domain.Entities.User", "StatusChangedByUser")
                        .WithMany()
                        .HasForeignKey("StatusChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KOP.Domain.Entities.Submission", "Submission")
                        .WithMany("SubmissionEvents")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StatusChangedByUser");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("KOP.Domain.Entities.SubmissionSubjectOrgUnit", b =>
                {
                    b.HasOne("KOP.Domain.Entities.OrganizationalUnit", "SubjectOrgUnit")
                        .WithMany()
                        .HasForeignKey("SubjectOrgUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KOP.Domain.Entities.Submission", "Submission")
                        .WithMany("SubjectOrgUnits")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubjectOrgUnit");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("KOP.Domain.Entities.TopothetisiStelexous", b =>
                {
                    b.HasOne("KOP.Domain.Entities.OrganizationalUnit", "OrganizationalUnit")
                        .WithMany("TopothetiseisProsopikou")
                        .HasForeignKey("OrgUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KOP.Domain.Entities.StoixeioKostous", "StoixeioKostous")
                        .WithMany("TopothetiseisProsopikou")
                        .HasForeignKey("StoixeioKostousId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrganizationalUnit");

                    b.Navigation("StoixeioKostous");
                });

            modelBuilder.Entity("KOP.Domain.Entities.TyposPtitikouMesou", b =>
                {
                    b.HasOne("KOP.Domain.Entities.KatigoriaPtitikouMesou", "KatigoriaPtitikouMesou")
                        .WithMany("TypoiPtitikonMeson")
                        .HasForeignKey("KatigoriaPtitikouMesouId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KatigoriaPtitikouMesou");
                });

            modelBuilder.Entity("KOP.Domain.Entities.TyposPtitikouMesouOrgUnit", b =>
                {
                    b.HasOne("KOP.Domain.Entities.OrganizationalUnit", "OrgUnit")
                        .WithMany("TypoiPtitikonMesonOrgUnits")
                        .HasForeignKey("OrgUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KOP.Domain.Entities.TyposPtitikouMesou", "TyposPtitikouMesou")
                        .WithMany("TypoiPtitikonMesonOrgUnits")
                        .HasForeignKey("TyposPtitikouMesouId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrgUnit");

                    b.Navigation("TyposPtitikouMesou");
                });

            modelBuilder.Entity("KOP.Domain.Entities.User", b =>
                {
                    b.HasOne("KOP.Domain.Entities.OrganizationalUnit", "OrgUnit")
                        .WithMany("Users")
                        .HasForeignKey("OrgUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrgUnit");
                });

            modelBuilder.Entity("KOP.Domain.Entities.ValueForAleOdoiporikon", b =>
                {
                    b.HasOne("KOP.Domain.Entities.Ale", "Ale")
                        .WithMany()
                        .HasForeignKey("AleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KOP.Domain.Entities.YpodeigmaEntry", "Entry")
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ale");

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("KOP.Domain.Entities.Ypodeigma", b =>
                {
                    b.HasOne("KOP.Domain.Entities.KyrioStoixeio", "KyrioStoixeio")
                        .WithMany("Ypodeigmata")
                        .HasForeignKey("KyrioStoixeioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KyrioStoixeio");
                });

            modelBuilder.Entity("KOP.Domain.Entities.YpodeigmaEntry", b =>
                {
                    b.HasOne("KOP.Domain.Entities.OrganizationalUnit", "MoiraOrgUnit")
                        .WithMany()
                        .HasForeignKey("MoiraOrgUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KOP.Domain.Entities.OrganizationalUnit", "MonadaOrgUnit")
                        .WithMany()
                        .HasForeignKey("MonadaOrgUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KOP.Domain.Entities.StoixeioKostous", "StoixeioKostous")
                        .WithMany()
                        .HasForeignKey("StoixeioKostousId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KOP.Domain.Entities.Submission", "Submission")
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MoiraOrgUnit");

                    b.Navigation("MonadaOrgUnit");

                    b.Navigation("StoixeioKostous");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("KOP.Domain.Entities.YpodeigmaSubmissionScope", b =>
                {
                    b.HasOne("KOP.Domain.Entities.OrganizationalUnit", "ResponsibleOrgUnit")
                        .WithMany()
                        .HasForeignKey("ResponsibleOrgUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KOP.Domain.Entities.OrganizationalUnit", "SubjectOrgUnit")
                        .WithMany()
                        .HasForeignKey("SubjectOrgUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KOP.Domain.Entities.Ypodeigma", "Ypodeigma")
                        .WithMany()
                        .HasForeignKey("YpodeigmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResponsibleOrgUnit");

                    b.Navigation("SubjectOrgUnit");

                    b.Navigation("Ypodeigma");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.HasOne("KOP.Domain.Entities.User", "InsertedByUser")
                        .WithMany()
                        .HasForeignKey("InsertedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KOP.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsertedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KOP.Domain.Entities.KatigoriaPtitikouMesou", b =>
                {
                    b.Navigation("TypoiPtitikonMeson");
                });

            modelBuilder.Entity("KOP.Domain.Entities.KyrioStoixeio", b =>
                {
                    b.Navigation("StoixeiaKostous");

                    b.Navigation("Ypodeigmata");
                });

            modelBuilder.Entity("KOP.Domain.Entities.OrganizationalUnit", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("MiktesApodoxesAnaEtosOrgUnitStoixeioKostous");

                    b.Navigation("Submissions");

                    b.Navigation("TopothetiseisProsopikou");

                    b.Navigation("TypoiPtitikonMesonOrgUnits");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("KOP.Domain.Entities.StoixeioKostous", b =>
                {
                    b.Navigation("MiktesApodoxesAnaEtosOrgUnitStoixeioKostous");

                    b.Navigation("TopothetiseisProsopikou");
                });

            modelBuilder.Entity("KOP.Domain.Entities.Submission", b =>
                {
                    b.Navigation("SubjectOrgUnits");

                    b.Navigation("SubmissionEvents");
                });

            modelBuilder.Entity("KOP.Domain.Entities.TyposPtitikouMesou", b =>
                {
                    b.Navigation("TypoiPtitikonMesonOrgUnits");
                });

            modelBuilder.Entity("KOP.Domain.Entities.User", b =>
                {
                    b.Navigation("CreatedSubmissions");

                    b.Navigation("InsertedAccessGrants");

                    b.Navigation("ReceivedAccessGrants");

                    b.Navigation("UpdatedSubmissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("KOP.Domain.Entities.Ypodeigma", b =>
                {
                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
